name: Kevin Morales
title: kevin morales
description: Front End Developer | Chicago, IL
url: http://kevinmoral.es
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ['node_modules', 'gulpfile.js', 'package.json']
redcarpet:
  extensions:
    [
      'no_intra_emphasis',
      'fenced_code_blocks',
      'autolink',
      'strikethrough',
      'superscript',
    ]
github_username: kgmorales
linkedin_username: kevingmorales
codepen_username: kgmorales
email: kmorales076@gmail.com
plugins: [jekyll-paginate]
paginate: 5
future: true
permalink: pretty
#default settings
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      author: Kevin Morales
      layout: 'post'
      category: 'blog'
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
