# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gnarfugh
email: kmorales076@gmail.com
description: Front End Developer from Chicago, IL
#baseurl: "#🍕" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com/" # the base hostname & protocol for your site
twitter_username: gnarfugh
github_username:  gnarfugh

# Build settings
markdown: kramdown
permalink: /:title
#default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Kevin Morales
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
